title: DevOps Wiki
description: Personal wiki for DevOps!
theme: just-the-docs
color_scheme: wiki

url: https://duchuyta.github.io/DevOps/

aux_links:
  Template Repository: https://github.com/duchuyta/DevOps
