title: DevOps notes
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://duchuyta.github.io/DevOps/

aux_links:
  Template Repository: https://github.com/duchuyta/DevOps
